name: GitHub Actions Security Analysis with zizmor 🌈

on:
  push:
    paths: &paths
      - '.github/**.yml'
      - '.github/**.yaml'
  pull_request:
    paths: *paths

permissions:
  contents: read

jobs:
  zizmor:
    uses: yiisoft/actions/.github/workflows/zizmor.yml@master
